{"timestamp":"2025-07-17T21:02:09.328910","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-17T21:02:09.330501","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/dag2.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-17T21:02:13.381825","level":"info","event":"Exporting data for table: sales_managers","logger":"unusual_prefix_b32ce7d530ba84fdd1796e135f31aa77492b4d52_dag2"}
{"timestamp":"2025-07-17T21:02:15.861956","level":"info","event":"Connection Retrieved 'postgres_default'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-17T21:02:16.165189","level":"warning","event":"/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py:482: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)\n","logger":"py.warnings"}
{"timestamp":"2025-07-17T21:02:16.386173","level":"error","event":"Error exporting data for table: sales_managers. Error: BaseHook.__init__() got an unexpected keyword argument 'google_cloud_storage_conn_id'","logger":"unusual_prefix_b32ce7d530ba84fdd1796e135f31aa77492b4d52_dag2"}
{"timestamp":"2025-07-17T21:02:16.386904","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"TypeError","exc_value":"BaseHook.__init__() got an unexpected keyword argument 'google_cloud_storage_conn_id'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/dag2.py","lineno":85,"name":"_export_to_gcs"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py","lineno":277,"name":"__init__"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-17T21:02:16.925484","level":"error","event":"Top level error","logger":"task","error_detail":[{"exc_type":"UndefinedError","exc_value":"'airflow.sdk.execution_time.task_runner.RuntimeTaskInstance object' has no attribute 'log_url'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1297,"name":"main"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1277,"name":"finalize"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1105,"name":"_send_task_error_email"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py","lineno":411,"name":"_get_email_subject_content"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py","lineno":408,"name":"render"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py","lineno":244,"name":"render_template_to_string"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py","lineno":239,"name":"render_template"},{"filename":"<template>","lineno":22,"name":"root"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/jinja2/runtime.py","lineno":859,"name":"_fail_with_undefined_error"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-17T21:02:22.401221Z","level":"warning","event":"Process exited abnormally","exit_code":1,"logger":"task"}
